apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: latest
    chart: loki
    helm:
      valueFiles:
        - ../helm-values/loki-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
