apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: latest
    chart: prometheus
    helm:
      valueFiles:
        - ../helm-values/prometheus-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
