apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitvavo-scalper
  namespace: bitvavo-scalper
spec:
  project: default
  source:
    repoURL: "https://github.com/stolkie78/bitvavo-scalper.git"
    path: "kubernetes/"
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: bitvavo-scalper
  syncPolicy:
    automated:
      prune: true
      selfHeal: true