adminPassword: "admin123"

persistence:
  enabled: true
  storageClassName: standard
  size: 5Gi

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - grafana.example.com
